### ISSUE TITLE
[Bug] No settings options

### ISSUE THREAD

**Issue by Nanorithm** [yofukashino/DiscordBypasses#1]
I think after the recent discord update, for some reason this plugin isn't showing settings.

![image](https://user-images.githubusercontent.com/13856563/231882749-70e9f33f-6924-4cd0-962b-12f47f703117.png)

**Comment by 11sap** [comment]
For now, you can download this here: <a href="https://github.com/11sap/DiscordBypasses/releases/tag/v0.9.5-qf">download</a> 
There is no ClientThemebypass, but the plugin works :)

**Comment by yofukashino** [comment]
Nice timing I was planning to fix it today lol

**Comment by yofukashino** [comment]
should be fixed in latest update
