### ISSUE TITLE
(Bug) (idk where) auto update and install does not work

### ISSUE THREAD

**Issue by Blazzycrafter** [yofukashino/DiscordBypasses#3]
my replugged version is *Replugged v4.6.5*
and the DB version is 1.0.9 (auto update does not work...)

problem i cant auto update and if i try to install it per install button the website says:
![image](https://github.com/Tharki-God/DiscordBypasses/assets/39300111/62c67f67-5c45-42eb-af5c-8bb3bc270ecb)

**Comment by yofukashino** [comment]
replugged issue will be fixed in next update

**Comment by Blazzycrafter** [comment]
K
